### ISSUE TITLE
Compiled Version

### ISSUE THREAD

**Issue by diver66** [UltraStar-Deluxe/UltraStar-Manager#12]
Where can I download the latest compiled version for windows 10 ?

**Comment by basisbit** [comment]
latest stable is available at https://sourceforge.net/projects/uman/

**Comment by bohning** [comment]
Latest CI build can be found e.g. [here](https://ci.appveyor.com/project/bohning/ultrastar-manager/builds/37309561/job/akd7mn508ct3k6uo/artifacts).
