### ISSUE TITLE
Suggestion: "Change Tag"-Task

### ISSUE THREAD

**Issue by natrius** [UltraStar-Deluxe/UltraStar-Manager#13]
I mistakenly did the "Set #Genre Tag if it is empty" for a lot of songs to "English" because i read partly the next task. And now there is no way to just mulit-select the songs and just change it to "Rock", for example.

**Comment by bohning** [comment]
In fact, there is. Simply select all the songs you want to change and enger the genre into the genre field.

**Comment by natrius** [comment]
Oh, i never saw there there are multiple tabs on the left pane. Never expected them on the bottom and default setting was "Web Information" so i was stuck there. Thanks.

**Comment by bohning** [comment]
Ah, good hint. It shouldn't be on web information by default, I will make sure to change that. I recently added language detection capabilities, so that a double click will transfer the detected language(s) to the #LANGUAGE tag (as it is currently working with artist, title, and year)
