### ISSUE TITLE
Are Build and Run up to date?

### ISSUE THREAD

**Issue by BanCrash** [UltraStar-Deluxe/UltraStar-Manager#14]
Hello, I tried to compile the program following the instructions but the compiler shows issues and won't compile. I tried to compile albumartex.pro:

![image](https://user-images.githubusercontent.com/11770760/104112241-96299880-52ec-11eb-8cf6-a7e4a920040c.png)

UltraStar-Manager.pro;

![image](https://user-images.githubusercontent.com/11770760/104112253-b48f9400-52ec-11eb-991e-b9b89a48a76c.png)

I'm using Qt Creator 4.14.0, with Desktop Qt 5.9.9 MinGW 5.3.0 32bit for C++.

**Comment by bohning** [comment]
Hi!

’SkipEmptyParts’ was moved from the QString to the Qt namespace starting with Qt 5.15.2, I believe. So if you want to to compile, you need a more recent version of Qt.

However, automatic retrieval of cover art has been broken for ages (yes, all three of them), unfortunately. This is particularly true for albumartexchange, since it prohibits programmatic download of cover files.

Try compiling with Qt 5.15.2 MinGW 64bit.

**Comment by BanCrash** [comment]
Thanks for the information, I was able to compile all the plugins, but the main project is still not compiling:

![image](https://user-images.githubusercontent.com/11770760/104125005-5c8c7800-5354-11eb-84c2-5cf5c0a77093.png)

I tried also with this commit version: https://github.com/UltraStar-Deluxe/UltraStar-Manager/tree/863aca32423af6cd1435b04e1ef3577a1a090e51 but won't compile neither:

![image](https://user-images.githubusercontent.com/11770760/104125088-d02e8500-5354-11eb-9f0e-f94783b09ab8.png)

Maybe I need to install something else?

![image](https://user-images.githubusercontent.com/11770760/104125118-fb18d900-5354-11eb-8ed2-f64d9aa0579f.png)

![image](https://user-images.githubusercontent.com/11770760/104125123-0409aa80-5355-11eb-9b40-3c5e5e8fdfeb.png)

**Comment by bohning** [comment]
I just pushed two additional commits, I just fixed Windows compilation for myself yesterday (I have a Mac). Let me know if it compiles with the latest master.

**Comment by BanCrash** [comment]
With the last master, I get another compiling error, this time 2 instead 1:

![image](https://user-images.githubusercontent.com/11770760/104127444-57362a00-5362-11eb-8a8f-3869ef9bc16c.png)

**Comment by bohning** [comment]
Can you please try to compile in Release? What’s the output in tab "4 Compilation"?

**Comment by BanCrash** [comment]
I compiled on Release, and I have this error:

```
process_begin: CreateProcess(NULL, windeployqt64releaseonly --release --no-translations --no-system-d3d-compiler --compiler-runtime --no-angle --no-opengl-sw ..\bin\release\UltraStar-Manager.exe, ...) failed.
make (e=2): El sistema no puede encontrar el archivo especificado. -> This means,  "The system cannot find the specified file"
mingw32-make[1]: *** [Makefile.Release:519: ../bin/release/UltraStar-Manager.exe] Error 2
mingw32-make[1]: Leaving directory 'E:/UltraStar-Manager-master (2)/UltraStar-Manager-master/src'
mingw32-make: *** [Makefile:45: release] Error 2
16:45:16: The process "D:\Programas\Qt\Tools\mingw810_64\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project UltraStar-Manager (kit: Desktop Qt 5.15.2 MinGW 64-bit)
When executing step "Make"
16:45:16: Elapsed time: 01:41.
```

I translated  the error, which is " The system cannot find the specified file"

**Comment by bohning** [comment]
Ah, we’re getting closer. Unfortunately, there’s a bug in Qt 5.15.2 windeployqt.exe, read here:

https://forum.qt.io/topic/109779/windeployqt-exe-comes-with-qt-5-14-not-copy-the-dlls-to-the-app-directory/8

Download windeployqt64releaseonly.exe and put it in the respective bin folder.

**Comment by BanCrash** [comment]
I also had to install NSIS (maybe you can add to the readme too?) before it compiles but after downloading the file you told me and installing NSIS it compiles and now I can use it. And I just test the program and it works, so it's finally compiled well!

Thanks you so much for all your help and time!!

**Comment by bohning** [comment]
True, forgot about NSIS. This step can be commented out in the .pro file in case you don’t need an installer, then NSIS is not required. But I will add it to the readme. I consider the windeployqt issue temporary and thus I will not add the hack with windeployqt64releaseonly.exe to the readme.

Let me know how the latest master works for you – I heard from some testers that it crashes (can’t reproduce unfortunately). Check out the web information panel – double clicking the (yellow/red) smiley will transfer the info to the song file (I use this feature to mostly check song language, song year, correct spelling of artist/title).

**Comment by bohning** [comment]
Finally fixed the Windows appveyor CI build. You can find automatic build artefacts here:

https://ci.appveyor.com/project/bohning/ultrastar-manager/build/artifacts

**Comment by BanCrash** [comment]
Hello, thanks for the tip, I am using it and it's very useful! But about crashes yeah, I have, I don't know what happens because it happens randomly, but they happen indeed. Is there anything I can do to see if I can point to you the cause? Like use a debugging version?

And thanks for fixing the automatic building!

**Comment by bohning** [comment]
I will have to investigate further, I can build on Windows in my virtual machine and will see what I can do. If there is anything you observe that could be the cause, let me know.

**Comment by BanCrash** [comment]
If I click into a song, and then fast click into another, and then again fast into another, the program will eventually crash. Sometimes on the second click, sometimes on the fourth, but I don't think I need more of 3 or 4 clicks to achieve the crash.

So maybe I'm wrong, but my guess it's the program doesn't end of doing something with the song, and if you try to load another song before ending the loading of the previous, it will crash. Like I said, It's only my guess, maybe the real cause if something different.

**Comment by bohning** [comment]
That’s a good hint, I will try to reproduce and investigate. I will see if I can get it to crash that way on mac as well (never had any issues so far, this just surfaced after fixing the Windows build).

**Comment by BanCrash** [comment]
Perfect, If I can do anything for help just let me know.

**Comment by BanCrash** [comment]
Well, this is odd. The auto-compiled version is not crashing for me, but it doesn't find any song in the web. It always says "song not found".

So, apparently, if search is working, the program crash. If search is not working, the program will not crash...

**Comment by bohning** [comment]
Same here, this is new. I will have to investigate.

**Comment by bohning** [comment]
It seems that swisscharts.com have overhauled their website just recently, so this indeed needs some adaptation.

**Comment by bohning** [comment]
@BanCrash Please try with the latest master, it seems to be fixed by my [latest commit](https://github.com/UltraStar-Deluxe/UltraStar-Manager/commit/ca85a051f7aaffdb9d4089d79d1d68f163c6eaff).

**Comment by BanCrash** [comment]
Hello again, yes, the swisscharts is fixed now, but the crash issue is back again with it. So It has to be something related with that.

Btw, discogs and AllMusic are unavailable right now, didn't they? I wanted to see if the crash happens with those too, but I can't activate them.

**Comment by bohning** [comment]
> Hello again, yes, the swisscharts is fixed now, but the crash issue is back again with it. So It has to be something related with that.

I will try to find out why this causes a crash on Windows (but not on Mac).

> Btw, discogs and AllMusic are unavailable right now, didn't they? I wanted to see if the crash happens with those too, but I can't activate them.

Discogs and AllMusic were experimental, I will disable/delete them.

**Comment by bohning** [comment]
@BanCrash can you disable swisscharts in the WebInformation tab and try to reproduce the crash?

**Comment by BanCrash** [comment]
This is so odd, with every test I'm more confused.

I have made test this morning and I was able to crash the program on some scenarios, like having it disabled. But right now I can't achieve the crashing even with swisscharts enabled, at least not as easy as before (I achieve a couple of times, but after a lot of clicks, and I can't replicate right now).

**Comment by bohning** [comment]
Very strange indeed. So what’s the current status? Is is (mostly) stable?

**Comment by BanCrash** [comment]
Okay, the bad news are the crashes are not gone.

The good news it's I found why It didn't crash earlier. If I open the program, and I don't touch it for a long time (20 minutes), it won't crash, or at least not as easy as before.

**Comment by BanCrash** [comment]
@bohning about crashing, I had disabled swisscharts and it didn't crash. I enable it back after that the crashes come back.

For some reason when swisscharts is enabled the program will crash at some point.

**Comment by bohning** [comment]
Happy to hear that!
