### ISSUE TITLE
Uman can't add (some?) non-english characters to a playlist

### ISSUE THREAD

**Issue by BanCrash** [UltraStar-Deluxe/UltraStar-Manager#15]
Hello. I found that if a song has non-english characters, uman will add to the playlist with bad characters, resulting of being added wrong.

For example, if the song includes 

> ¿Qué

It will add to the .upl file:

> Â¿QuÃ©

or if it includes

> tú

It will add

> tÃº

In spanish, we use those characters which can make this issue:

> ¿ á é í ó ú ñ Á É Í Ó Ú Ñ

And also I found this issue on the letter

> Ö

which is write as

> Ã–

**Comment by bohning** [comment]
Ah, a classic encoding problem. Which encodings do the respective files have, UTF-8 or CP1252?

![image](https://user-images.githubusercontent.com/1497707/104908447-c6290980-5986-11eb-94f6-b2a309b0fcbc.png)

**Comment by BanCrash** [comment]
Notepad++ says UTF-8

![image](https://user-images.githubusercontent.com/11770760/104908624-0ab4a500-5987-11eb-902f-b0c0246cde39.png)

**Comment by bohning** [comment]
Hmm, that’s strange. I just checked with two songs that contain German umlauts, both saved in UTF-8 (you can see that in UltraStar-Manager as well as the first entry in the song information tab), and the resulting playlist is correct (playlists are saved in UTF-8 as well):

```
######################################
#Ultrastar Deluxe Playlist Format v1.0
Playlist New Playlist with 2 Songs.
######################################
#Name: New Playlist
#Songs:
Herbert Grönemeyer : 16 - Marie
Kettcar : Sommer ’89 (Er Schnitt Löcher In Den Zaun)
```

Can you provide with a sample file where this happens?

**Comment by BanCrash** [comment]
Yes, you are right, now it's working, I don't know what happened then. Maybe on a crash playlist got corrupted or something like that.

**Comment by BanCrash** [comment]
I have to open this again since the issue is not solved, although the issue is different that I thought.

When you add a song to the playlist, is added properly, but after reloading uman, It won't detect it properly, and If you save changes to the playlist then it will save with the modified name.

I added "tést - Ajáa" to the playlist Test:

![image](https://user-images.githubusercontent.com/11770760/105507810-f268c100-5ccb-11eb-82d4-39666b562028.png)

![image](https://user-images.githubusercontent.com/11770760/105508071-3956b680-5ccc-11eb-8886-dd50f237e651.png)

After closing the program and opening it again:

![image](https://user-images.githubusercontent.com/11770760/105507921-0f9d8f80-5ccc-11eb-9298-5dd5e55a6f66.png)

And If I add again the same song:

![image](https://user-images.githubusercontent.com/11770760/105508144-52f7fe00-5ccc-11eb-8acd-63d642014b0c.png)

![image](https://user-images.githubusercontent.com/11770760/105508158-57bcb200-5ccc-11eb-9e46-5e483c0d8220.png)

**Comment by bohning** [comment]
Thanks for reopening, I will look into it.

**Comment by bohning** [comment]
Ah, I see where the problem is. I believe USDX outputs in CP1252, so UltraStar-Manager assumes CP1252 input when reading UPL files, but outputs UTF-8. So when reading an UTF-8 UPL file (that UltraStar-Manager itself created), it goes wrong because it reads UTF-8 as CP1252.

Not sure where to go with this information.

**Comment by basisbit** [comment]
current versions of USDX should output playlists as UTF8, as far as I know.

**Comment by bohning** [comment]
Thanks for the feedback, @basisbit. Then the latest commit fix the issue and Ultrastar-Manager expects playlist files in UTF-8.

**Comment by BanCrash** [comment]
![image](https://user-images.githubusercontent.com/11770760/105563260-bcecc380-5d1d-11eb-83fd-12a5e117f6cd.png)

Seems to be not solved yet with the last commit...

**Comment by bohning** [comment]
Oh, yeah. I was too quick and missed the other lines. Please try with the [latest build](https://ci.appveyor.com/project/bohning/ultrastar-manager/builds/37409514/job/wu7y7nltx2o1n1mg/artifacts).

**Comment by BanCrash** [comment]
![image](https://user-images.githubusercontent.com/11770760/105579162-11775980-5d85-11eb-9de0-de032fe1b45b.png)

Okay, now it seems to be solved. Thanks again!
