### ISSUE TITLE
QT::ENDL issue

### ISSUE THREAD

**Issue by marts2007** [UltraStar-Deluxe/UltraStar-Manager#16]
There is no QT::endl in QT < 5.14
fast fix:

```
#include <QtGlobal>

#if QT_VERSION >= QT_VERSION_CHECK(5,14,0)
#define ENDL Qt::endl
#else
#define ENDL endl
#endif
```

and replace QT::endl with ENDL

**Comment by marts2007** [comment]
also there is no QT::SkipEmptyParts in QT <= 5.12 so in order to build it i had to replace it with QString::SkipEmptyParts

**Comment by marts2007** [comment]
and I had to install libcld2-dev

**Comment by bohning** [comment]
@marts2007 Thanks for reporting and providing a workaround =)

**Comment by DeinAlptraum** [comment]
We only support QT6 now, and implemented the changes you mentioned. `libcld2-dev` has also been added to the installation instructions
