### ISSUE TITLE
.m4a audio files are not detected as supported but they are supported.

### ISSUE THREAD

**Issue by suiluj** [UltraStar-Deluxe/UltraStar-Manager#18]
At the moment I get a lot of missing audio file errors because I use .m4a audio files instead of .mp3

uman return an error

```
File type unsupported: ...
```

But this is wrong because usdx supports .m4a files.

**Comment by bohning** [comment]
https://github.com/UltraStar-Deluxe/UltraStar-Manager/blob/d0f7e879d856f487ae0abed9d484c615f13ae1ee/src/QUSongSupport.cpp#L91

**Comment by suiluj** [comment]
okay so this change was after the last release...

i guess i have to compile a new version for macos myself *fingers crossed* 😆

**Comment by bohning** [comment]
I am on Mac, so it should indeed work fine. Let me know when you are having troubles.

**Comment by suiluj** [comment]
Hi thanks for the info.

I tried it and the plugins worked all fine (only a few warnings...)

In the end while creating the .app there was an error but it the app still works for some reason.
Now I opened the app directly and was able to chose a library path (instead of the automator service like before)

here are the last few logs while building:

```
ib -L../lib/MacOS -lcld2 -L/usr/local/Cellar/taglib/1.13/lib -ltag -L/usr/local/Cellar/media-info/22.09/lib -lmediainfo -lz -lzen -lpthread -framework QtPrintSupport -framework QtWidgets -framework QtMultimedia -framework QtGui -framework AppKit -framework Metal -framework QtNetwork -framework QtXml -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL
ld: warning: dylib (/usr/local/Cellar/taglib/1.13/lib/libtag.dylib) was built for newer macOS version (11.0) than being linked (10.13)ld: warning: dylib (../lib/MacOS/libcld2.dylib) was built for newer macOS version (10.15) than being linked (10.13)

ld: warning: dylib (/usr/local/Cellar/media-info/22.09/lib/libmediainfo.dylib) was built for newer macOS version (11.0) than being linked (10.13)
ld: warning: dylib (/usr/local/Cellar/media-info/22.09/lib/libzen.dylib) was built for newer macOS version (11.0) than being linked (10.13)
macdeployqt ../bin/release/UltraStar-Manager.app -libpath=../lib/MacOS -always-overwrite
install_name_tool -change /usr/local/Cellar/media-info/20.08/lib/libzen.0.dylib @executable_path/../Frameworks/libzen.0.dylib ../bin/release/UltraStar-Manager.app/Contents/Frameworks/libmediainfo.0.dylib
create-dmg --volname UltraStar-Manager --volicon resources/UltraStar-Manager.icns --app-drop-link 350 170 --background ../setup/macx/img/UltraStar-Manager_bg.png --hide-extension UltraStar-Manager.app --window-size 500 300 --text-size 14 --icon-size 64 --icon UltraStar-Manager.app 150 170 --no-internet-enable --skip-jenkins ../bin/release/UltraStar-Manager.dmg ../bin/release/UltraStar-Manager.app/
make: create-dmg: No such file or directory
make: *** [../bin/release/UltraStar-Manager.app/Contents/MacOS/UltraStar-Manager] Error 1
```

I guess that I have to install a specific version of `taglib` and `mediainfo` or change a build parameter somewhere?

For qt5 I did the following to get `qmake` working with `qt5` (first I only installed qt5 but `qmake` was not found):

```
brew install qt

brew install qt@5
# or
brew reinstall qt@5

brew unlink qt
brew link qt@5 --force
```

I'm no expert at qt and compilation for cpp. So perhaps you have a hint for me?

My MacBook is from late 2013 and running Big Sur 11.7.1


Just wanted to let you know about these logs. Everything works for me so I am very happy! Thanks for this great software! :)

**Comment by suiluj** [comment]
@bohning hey just wanted to "buy you a coffee" or something but I noticed that you do not have github sponsor enabled. So if you want to just enable it. I noticed a buy me a coffee button for your other sync project but there is no paypal anymore.

Github sponsor is just simpler ;)

Really appreciate your work here 👍

**Comment by bohning** [comment]
You’d be my first supporter and I really appreciate that. Don’t know how to enable the Github sponsor, will look into it =) Thanks for the great feedback. Most of UltraStar Manager was written by Marcel Taeumel, who unfortunately is no longer active.

**Comment by suiluj** [comment]
Sounds good, i think you'll get a few more supporters in the future so just try it out! 😄 👍 
Then I like that you keep the UltraStar Manager alive. I use it often and it works great even with a lot of songs.
And now that I use my self compiled version it even shows the correct available audio tracks when I create a .csv report.
