### ISSUE TITLE
UTF-8 encoding option missing in self compiled version from master branch (only cp1252 or cp1250 available)

### ISSUE THREAD

**Issue by suiluj** [UltraStar-Deluxe/UltraStar-Manager#19]
Hello I noticed that the option to set the encoding default to utf8 is missing when I do a self compile for macos.
(for the release version 1.8.3 I could select utf8)

I did not notice any problems for my songs (most songs I checked had working special characters and german Umlaute but I just wanted to show this:
<img width="652" alt="image" src="https://user-images.githubusercontent.com/13067545/205453869-ed0ab244-cfd4-4e28-a56f-18c7b553c5a8.png">

**Comment by basisbit** [comment]
Using Ansi/Asci/codepages is not officially supported by UltraStar Deluxe any more. Please always use UTF-8 when saving files. As far as I know, UltraStar Manager follows that suggestion and now always saves as UTF-8, thus no need for such a dialog any more..

**Comment by bohning** [comment]
Exactly, I threw out the code a while ago. Everyone should finally migrate to UTF-8 =)

**Comment by suiluj** [comment]
Ah thanks good to know. I use utf-8 since forever so that's good news for me ;)
