### ISSUE TITLE
-isystem /usr/include in makefile causes build to fail

### ISSUE THREAD

**Issue by memo42** [UltraStar-Deluxe/UltraStar-Manager#3]
I tried building UltraStar-Manager on a current Ubuntu.
This resulted in an error claiming stdlib.h was not found.
Googeling brought up this: https://bugreports.qt.io/browse/QTBUG-53367

=> removing -isystem /usr/include from the makefile solved the problem for me.

**Comment by diver66** [comment]
hi there,

what did you do exactely, i have 13 occurances of -isystem /usr/include,
do i delete them all ?

`
MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DUNICODE -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -Isong -Isongdetails -Isongtree -Ireport -Itasks -Itasks/taskDialog -Ipreview -Iplaylist -Iplaylistdetails -Ifilter -Imonty -Imediaplayer -Isupport -Ipreferences -Iui -Iplugins -Iribbon -Islideshow -Ilyricseditor -Iscore -Iremoteimages -Iwebinfo -I../include/mediainfo -isystem /usr/include/taglib -isystem /usr/include -isystem /usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/x86_64-linux-gnu -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimedia -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Itmp/release -isystem /usr/include/libdrm -Iui -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64`

**Comment by memo42** [comment]
Just the one "-isystem /usr/include " 
But since the makefile is generated it's just a dirty workaround.
The latest comment in the link I posted looks promising...

**Comment by diver66** [comment]
How can I get this workaround to work, if I change the content of the file, it gets getting set back to the original, whats the magic to get your workaround runningt ?

**Comment by memo42** [comment]
Have you tried doing the change after the qmake and before the make?

**Comment by diver66** [comment]
good idea, i try :-)
