### ISSUE TITLE
Can a new version be released?

### ISSUE THREAD

**Issue by Baklap4** [UltraStar-Deluxe/UltraStar-Manager#40]
I'm running into the issue that the latest released version is pretty old (400 commits behind).

I don't want to install the whole developer tool-chain just to build it so i'd love it if you guys can create a new release :).

# EDIT

I did find the GH-Actions artifacts, however anonymous GH users cannot access these so please create a version for them

**Comment by DeinAlptraum** [comment]
Hi @Baklap4 that's absolutely planned. I actually wanted to do a release weeks ago already, but I'd like to get the ARM Mac build running first. Unfortunately, I couldn't find anyone to test the ARM build yet. I will ask around some more, and hope to get one out soon.

**Comment by DeinAlptraum** [comment]
A new version has just been released.

**Comment by theRoboxx** [comment]
> A new version has just been released.

Thanks a lot :heart:
