### ISSUE TITLE
Software is non-free because of libbass

### ISSUE THREAD

**Issue by Profpatsch** [UltraStar-Deluxe/UltraStar-Manager#5]
See https://github.com/UltraStar-Deluxe/UltraStar-Creator/issues/3

**Comment by bohning** [comment]
External BASS audio library has been replaced by internal QMediaPlayer.
See 1207199643b0e2db0fbf0cfa480bd9752604aa4a.

**Comment by Profpatsch** [comment]
Awesome!

**Comment by basisbit** [comment]
wow, you @bohning are amazing!
