### ISSUE TITLE
Building dependencies on linux

### ISSUE THREAD

**Issue by GWRon** [UltraStar-Deluxe/UltraStar-Manager#7]
`sudo apt-get install qtmultimedia5-dev libqt5multimediawidgets5 libqt5multimedia5-plugins libqt5multimedia5`
is needed to build the application.

Also the building instructions for the plugins/main binary contain directory changes but do not leave them afterwards.

**Comment by redflash13** [comment]
I had similiar issue building the project on Ubuntu 16.04 and 17.10 as well as #3 when trying to build on Ubuntu 17.10

I summarized the steps I finally did. I found as well some typos in the original build instructions. Maybe it's worth to update these:

1. Install the Qt framework:
	> sudo apt-get install qt5-default qttools5-dev-tools qtbase5-dev-tools qt5-qmake qtmultimedia5-dev libqt5multimediawidgets5 libqt5multimedia5-plugins libqt5multimedia5
2. Install dependencies:
	> sudo apt-get install libtag1-dev libmediainfo-dev libzen-dev
3. Clone the repository:
	> git clone https://github.com/UltraStar-Deluxe/UltraStar-Manager && cd UltraStar-Manager
4. Compile UltraStar-Manager plugins
    option a) from command line
	> cd src/plugins/audiotag && qmake audiotag.pro && make && cd ../../../
        > cd src/plugins/cleanup && qmake cleanup.pro && make && cd ../../../
        > cd src/plugins/lyric && qmake lyric.pro && make && cd ../../../
        > cd src/plugins/preparatory && qmake preparatory.pro && make && cd ../../../
        > cd src/plugins/rename && qmake rename.pro && make && cd ../../../
    option b) using Qt Creator: open the respective *.pro files in Qt Creator, disable shadow build in Project tab, then build
5. Compile UltraStar-Manager
    option a) from command line:
	> cd src && qmake UltraStar-Manager.pro
	> make && cd ../
	Note: if "make" fails with "stdlib.h was not found", open makefile and remove "-isystem /usr/include " from it. Afterwards, run "make" again.
    option b) using Qt Creator:
	open UltraStar-Manager.pro in Qt Creator, disable shadow build in Project tab, then build and run
6. Run UltraStar-Manager
	> bin/release/UltraStar-Manager
